// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/config"
	"github.com/go-kratos/kratos/v2/log"
	"user-service/internal/server"
	"user-service/internal/transport/grpc"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(c config.Config, logger log.Logger) (*kratos.App, func(), error) {
	userService := grpc.NewUserService()
	grpcServer := server.NewGRPCServer(logger, userService)
	httpServer := server.NewHTTPServer(logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
