// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/config"
	"github.com/go-kratos/kratos/v2/log"

	"notification-service/internal/data"
	"notification-service/internal/server"
)

// wireApp initializes the application
func wireApp(c config.Config, logger log.Logger) (*kratos.App, func(), error) {
	// Create MongoDB client
	mongoClient, err := data.NewMongoClient(c, logger)
	if err != nil {
		return nil, nil, err
	}

	// Create Redis client
	redisClient, err := data.NewRedisClient(c, logger)
	if err != nil {
		return nil, nil, err
	}

	// Create Data layer
	dataData, dataCleanup, err := data.NewData(mongoClient, redisClient, logger)
	if err != nil {
		return nil, nil, err
	}
	_ = dataData // Data is used for cleanup only

	// Create Kafka Producer
	kafkaProducer, producerCleanup, err := data.NewKafkaProducer(c, logger)
	if err != nil {
		dataCleanup()
		return nil, nil, err
	}

	// Create Kafka Consumer
	kafkaConsumer, err := data.NewKafkaConsumer(c, logger)
	if err != nil {
		producerCleanup()
		dataCleanup()
		return nil, nil, err
	}

	// Create Notification Repository
	notificationRepo := data.NewNotificationRepository(mongoClient, c, logger)

	// Create Idempotency Store
	idempotencyStore := data.NewIdempotencyStore(redisClient)

	// Create Realtime Publisher (Redis Pub/Sub)
	realtimePublisher := data.NewRealtimePublisher(redisClient)

	// Create Template Renderer
	templateRenderer := data.NewTemplateRenderer()

	// Create Multi-Channel Sender
	multiChannelSender := data.NewMultiChannelSender(kafkaProducer, templateRenderer, c)

	// Create User Service Client
	userService, userServiceCleanup, err := data.NewUserServiceClient(c, logger)
	if err != nil {
		producerCleanup()
		dataCleanup()
		return nil, nil, err
	}

	// Create Dispatcher
	dispatcher := data.NewDispatcherRegistry(notificationRepo, multiChannelSender, idempotencyStore, realtimePublisher, userService)

	// Create Consumer Bootstrap
	consumerBootstrap := data.NewKafkaConsumerBootstrap(kafkaConsumer, dispatcher)

	// Create HTTP Server
	httpServer := server.NewHTTPServer(c, logger, consumerBootstrap)

	// Create Kratos App
	app := newApp(logger, httpServer)

	// Cleanup function
	cleanup := func() {
		if err := consumerBootstrap.Stop(); err != nil {
			log.NewHelper(logger).Errorf("failed to stop consumer: %v", err)
		}
		userServiceCleanup()
		producerCleanup()
		dataCleanup()
	}

	return app, cleanup, nil
}
