{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-prometheus
  labels:
    app: prometheus
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    protocol: TCP
{{- end }}
