{{- if .Values.consul.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "infrastructure.fullname" . }}-consul
  labels:
    app: consul
    {{- include "infrastructure.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "infrastructure.fullname" . }}-consul
  replicas: {{ .Values.consul.replicas }}
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: "{{ .Values.consul.image.repository }}:{{ .Values.consul.image.tag }}"
        args:
          - "agent"
          - "-server"
          - "-bootstrap-expect={{ .Values.consul.replicas }}"
          - "-ui"
          - "-bind=0.0.0.0"
          - "-client=0.0.0.0"
          - "-retry-join={{ include "infrastructure.fullname" . }}-consul-0.{{ include "infrastructure.fullname" . }}-consul.{{ .Release.Namespace }}.svc.cluster.local"
        ports:
        - name: http
          containerPort: 8500
        - name: dns
          containerPort: 8600
        - name: server
          containerPort: 8300
        - name: serf-lan
          containerPort: 8301
        - name: serf-wan
          containerPort: 8302
        resources:
          {{- toYaml .Values.consul.resources | nindent 10 }}
        {{- if .Values.consul.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /consul/data
        {{- end }}
  {{- if .Values.consul.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.consul.persistence.storageClass }}
      storageClassName: {{ .Values.consul.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.consul.persistence.size }}
  {{- end }}
{{- end }}
