apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-kong
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: serviceaccount
