# Kong subchart configuration
kong:
  image:
    repository: kong
    tag: "3.6"

  env:
    database: "off"
    declarative_config: /kong/kong.yaml
    log_level: debug

  # Tắt hoàn toàn Ingress Controller
  ingressController:
    enabled: false

  admin:
    enabled: true
    type: NodePort
    http:
      enabled: true
      servicePort: 8001

  proxy:
    enabled: true
    type: NodePort
    http:
      enabled: true
      nodePort: 30080

  deployment:
    kong:
      enabled: true
    # Mount ConfigMap vào Kong container
    userDefinedVolumes:
      - name: kong-config
        configMap:
          name: kong-config
    userDefinedVolumeMounts:
      - name: kong-config
        mountPath: /kong
