// syntax = "proto3";
//
// package task.v1;
//
// option go_package = "task-service/api/task/v1;taskv1";
//
// import "google/api/annotations.proto";
//
// service TaskService {
//   // CreateTask creates a new task
//   rpc CreateTask(CreateTaskRequest) returns (CreateTaskResponse) {
//     option (google.api.http) = {
//       post: "/v1/tasks"
//       body: "*"
//     };
//   }
//
//   // GetTask retrieves a task by ID
//   rpc GetTask(GetTaskRequest) returns (GetTaskResponse) {
//     option (google.api.http) = {
//       get: "/v1/tasks/{id}"
//     };
//   }
//
//   // ListTasks lists all tasks with pagination
//   rpc ListTasks(ListTasksRequest) returns (ListTasksResponse) {
//     option (google.api.http) = {
//       get: "/v1/tasks"
//     };
//   }
//
//   // AssignTask assigns a task to a user
//   rpc AssignTask(AssignTaskRequest) returns (AssignTaskResponse) {
//     option (google.api.http) = {
//       post: "/v1/tasks/{task_id}/assign"
//       body: "*"
//     };
//   }
//
//   // CompleteTask marks a task as completed
//   rpc CompleteTask(CompleteTaskRequest) returns (CompleteTaskResponse) {
//     option (google.api.http) = {
//       post: "/v1/tasks/{task_id}/complete"
//     };
//   }
// }
//
// // Task represents a task entity
// message Task {
//   string id = 1;
//   string title = 2;
//   string description = 3;
//   string status = 4;
//   string priority = 5;
//   string assignee_id = 6;
//   string project_id = 7;
//   string created_at = 8;
//   string updated_at = 9;
//   string due_date = 10;
// }
//
// // CreateTaskRequest
// message CreateTaskRequest {
//   string title = 1;
//   string description = 2;
//   string priority = 3;
//   string project_id = 4;
//   string due_date = 5;
// }
//
// message CreateTaskResponse {
//   Task task = 1;
// }
//
// // GetTaskRequest
// message GetTaskRequest {
//   string id = 1;
// }
//
// message GetTaskResponse {
//   Task task = 1;
// }
//
// // ListTasksRequest
// message ListTasksRequest {
//   int32 page = 1;
//   int32 page_size = 2;
//   string project_id = 3;
//   string assignee_id = 4;
//   string status = 5;
// }
//
// message ListTasksResponse {
//   repeated Task tasks = 1;
//   int32 total = 2;
// }
//
// // AssignTaskRequest
// message AssignTaskRequest {
//   string task_id = 1;
//   string assignee_id = 2;
// }
//
// message AssignTaskResponse {
//   Task task = 1;
// }
//
// // CompleteTaskRequest
// message CompleteTaskRequest {
//   string task_id = 1;
// }
//
// message CompleteTaskResponse {
//   Task task = 1;
// }

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: task/v1/task.proto

package taskv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_Hello_FullMethodName = "/task.v1.TaskService/Hello"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, TaskService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _TaskService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task/v1/task.proto",
}
