{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrastructure.fullname" . }}-kafka-headless
  labels:
    app: kafka
    {{- include "infrastructure.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
    protocol: TCP
{{- end }}
