{{- if .Values.sentry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-sentry
  labels:
    app: sentry
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: sentry
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
{{- end }}
