microservice:
  image:
    repository: "458108203578.dkr.ecr.ap-southeast-1.amazonaws.com/task-management/task-service"
    tag: "4ec4d93"
  replicaCount: 1
  envVarsSecret:
    MONGODB_URI: "mongodb://appuser:appPass123@mongodb.dev.svc.cluster.local:27017/task-service?authSource=task-service"
    REDIS_PASSWORD: "redisPass123"
    KAFKA_SASL_PASSWORD: ""
  envVarsCM:
    REDIS_HOST: "redis-cluster.redis.svc.cluster.local"
    REDIS_ADDR: "redis-cluster.redis.svc.cluster.local:6379"
    KAFKA_SASL_ENABLED: "false"
  autoscaling:
    enabled: false
  podDisruptionBudget:
    enabled: false
  topologySpreadConstraints: []
  metrics:
    enabled: false
  livenessProbe: null
  readinessProbe: null
  extraVolumes:
    - name: app-config
      configMap:
        name: task-service-app-config
  extraVolumeMounts:
    - name: app-config
      mountPath: /app/configs

appConfig:
  mongodbUri: "mongodb://appuser:appPass123@mongodb.dev.svc.cluster.local:27017/task-service?authSource=task-service"
  mongodbDatabase: "task-service"
  redisAddr: "redis-cluster.redis.svc.cluster.local:6379"
  redisPassword: "redisPass123"
