_format_version: "3.0"

services:
  - name: user-grpc-service
    url: grpc://user-service:50050

    routes:
      - name: user-grpc-route
        protocols:
          - grpc
        paths:
          - /user.v1.UserService
        strip_path: false

