{{- if .Values.jaeger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability.fullname" . }}-jaeger
  labels:
    app: jaeger
    {{- include "observability.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jaeger.replicas }}
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        ports:
        - name: ui
          containerPort: 16686
          protocol: TCP
        - name: collector-http
          containerPort: 14268
          protocol: TCP
        - name: collector-grpc
          containerPort: 14250
          protocol: TCP
        - name: zipkin
          containerPort: 9411
          protocol: TCP
        - name: otlp-grpc
          containerPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          protocol: TCP
        resources:
          {{- toYaml .Values.jaeger.resources | nindent 10 }}
{{- end }}
