{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-promtail-config
  labels:
    app: promtail
    {{- include "observability.labels" . | nindent 4 }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
    
    clients:
      - url: http://{{ include "observability.fullname" . }}-loki:3100/loki/api/v1/push
    
    positions:
      filename: /tmp/positions.yaml
    
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  labels:
    {{- include "observability.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
- apiGroups: [""]
  resources:
    - nodes
    - services
    - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: {{ .Release.Namespace }}
{{- end }}
