// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/config"
	"github.com/go-kratos/kratos/v2/log"
	"task-service/internal/data"
	"task-service/internal/server"
	"task-service/internal/transport/grpc"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(c config.Config, logger log.Logger) (*kratos.App, func(), error) {
	database, cleanup, err := data.NewMongoDatabase(c, logger)
	if err != nil {
		return nil, nil, err
	}
	taskRepository := data.NewTaskRepository(database, logger)
	taskService := grpc.NewTaskService(taskRepository, logger)
	grpcServer := server.NewGRPCServer(logger, taskService)
	httpServer := server.NewHTTPServer(logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
