apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    {{- include "logging.labels" . | nindent 4 }}
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://{{ .Release.Name }}-loki.{{ .Release.Namespace }}.svc.cluster.local:3100
      version: 1
      editable: false
      jsonData:
        maxLines: 1000
