global:
  storageClass: standard

image:
  tag: latest

auth:
  enabled: true
  rootUser: root
  rootPassword: password123

shards: 2
shardsvr:
  dataNode:
    replicaCount: 2
  arbiter:
    replicaCount: 0

configsvr:
  replicaCount: 2
  arbiter:
    replicaCount: 0

mongos:
  replicaCount: 2

persistence:
  enabled: true
  size: 2Gi

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m
