# Staging environment overrides
nginx:
  replicas: 2

kong:
  replicas: 2

kafka:
  replicas: 2
  persistence:
    size: 8Gi

redis:
  replicas: 1
  persistence:
    size: 3Gi

consul:
  replicas: 2
  persistence:
    size: 3Gi
