apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KONG_DATABASE
              value: {{ .Values.env.database | quote }}
            - name: KONG_DECLARATIVE_CONFIG
              value: {{ .Values.env.declarative_config | quote }}
          ports:
            - containerPort: 8000