apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    {{- range $name, $config := .Values.service.ports }}
    - port: {{ $config.port }}
      targetPort: {{ $config.targetPort | default $name }}
      protocol: {{ $config.protocol | default "TCP" }}
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "microservice.selectorLabels" . | nindent 4 }}
