{{- if .Values.kong.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrastructure.fullname" . }}-kong
  labels:
    app: kong
    {{- include "infrastructure.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kong.replicas }}
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag }}"
        env:
        - name: KONG_DATABASE
          value: {{ .Values.kong.env.database | quote }}
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/kong.yaml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_PLUGINS
          value: {{ .Values.kong.env.plugins | quote }}
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: grpc
          containerPort: 9080
          protocol: TCP
        resources:
          {{- toYaml .Values.kong.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
{{- end }}
