{{- if .Values.customConfig.enableInitScripts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "jenkins.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: agent
{{- end }}
